# Generated by Django 4.1.5 on 2023-01-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_photo_model'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['place__title', 'position']},
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='position',
            field=models.PositiveSmallIntegerField(db_index=True, default=0, verbose_name='Position'),
        ),
    ]
