# Generated by Django 4.1.5 on 2023-01-17 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_unique_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='description_long',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='place',
            old_name='description_short',
            new_name='short_description',
        ),
    ]
